### ISSUE TITLE
Npm for plyr.io & Shiki

### ISSUE THREAD

**Issue by c2tz** [c2tz/test-cerber-workflow#43]
Pour ajouter plyr et shiki dans github action a l'aide de nom fait comme suit : 

Pour installer Shiki Syntax Highlighter et Plyr.io HTML5 Player depuis GitHub Actions, vous pouvez suivre les étapes suivantes :

1. Assurez-vous d'avoir configuré votre workflow GitHub Actions correctement. Créez un fichier YAML (par exemple, `.github/workflows/install-dependencies.yml`) dans le répertoire `.github/workflows` de votre projet.

2. Dans le fichier YAML, spécifiez le déclencheur du workflow, tel qu'un push sur la branche principale :

```yaml
name: Install Dependencies
on:
  push:
    branches:
      - main
```

3. Ajoutez une étape pour installer les dépendances en utilisant npm. Vous pouvez utiliser l'action `actions/setup-node` pour configurer Node.js et npm dans votre environnement de workflow. Voici un exemple :

```yaml
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Shiki Syntax Highlighter
        run: npm install shiki

      - name: Install Plyr.io HTML5 Player
        run: npm install plyr
```

4. Enregistrez et poussez vos modifications vers le dépôt GitHub. Le workflow sera automatiquement déclenché, et les étapes d'installation des dépendances seront exécutées.

Une fois le workflow terminé, Shiki Syntax Highlighter et Plyr.io HTML5 Player seront installés dans l'environnement de votre workflow. Vous pouvez ensuite utiliser les bibliothèques comme prévu dans votre code.

Veillez à ajuster la version de Node.js et les étapes du workflow selon vos besoins spécifiques.

C'est tout ! Vous avez maintenant configuré GitHub Actions pour installer Shiki Syntax Highlighter et Plyr.io HTML5 Player lors de l'exécution du workflow.
